import = [
	"~/.config/alacritty/themes/themes/carbonfox.toml"
	# "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[shell]
program = "/usr/bin/zsh"

[keyboard]
bindings = [
{key = "Return", mods = "Control|Shift", action = "SpawnNewInstance"}
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
bright_foreground = "#6a9fb5"

[font]
size = 10.5

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[window.dimensions]
columns = 115
lines = 30
